// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnibusExpress.Infrastructure.Persistence;

#nullable disable

namespace OnibusExpress.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726054115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnibusExpress.Domain.Entities.Passageiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("passageiros", (string)null);
                });

            modelBuilder.Entity("OnibusExpress.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<int>("NumeroAssento")
                        .HasColumnType("integer");

                    b.Property<Guid>("PassageiroId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ViagemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("PassageiroId");

                    b.HasIndex("ViagemId", "NumeroAssento")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Confirmada'");

                    b.ToTable("reservas", (string)null);
                });

            modelBuilder.Entity("OnibusExpress.Domain.Entities.Rota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<TimeSpan>("DuracaoEstimada")
                        .HasColumnType("interval");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Origem", "Destino");

                    b.ToTable("rotas", (string)null);
                });

            modelBuilder.Entity("OnibusExpress.Domain.Entities.Viagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataHoraPartida")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalAssentos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RotaId", "DataHoraPartida");

                    b.ToTable("viagens", (string)null);
                });

            modelBuilder.Entity("OnibusExpress.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("OnibusExpress.Domain.Entities.Passageiro", "Passageiro")
                        .WithMany()
                        .HasForeignKey("PassageiroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnibusExpress.Domain.Entities.Viagem", "Viagem")
                        .WithMany()
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Passageiro");

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("OnibusExpress.Domain.Entities.Viagem", b =>
                {
                    b.HasOne("OnibusExpress.Domain.Entities.Rota", "Rota")
                        .WithMany()
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rota");
                });
#pragma warning restore 612, 618
        }
    }
}
